# Generated by Django 6.0.1 on 2026-01-18 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed', 'created_at']},
        ),
        migrations.AlterModelTable(
            name='task',
            table='tasks',
        ),
    ]
